### ISSUE TITLE
Problem With Database

### ISSUE THREAD

**Issue by mbelhassen** [UnamSanctam/UnamWebPanel#268]
I have a problem with database
![error](https://github.com/UnamSanctam/UnamWebPanel/assets/79266823/6cc10907-c1f0-4941-81b2-b68161d11d96)

**Comment by UnamSanctam** [comment]
Looks like it couldn't read the database file, are you sure that it's present on the disk and that the webserver user has read permissions to the file?

**Comment by mbelhassen** [comment]
yes

**Comment by mbelhassen** [comment]
yes disk isn't full and i have disable hashrate to see but it's the same problem apear after few miniutes , i have clear the database and reinstall a new one but the same problem apear

**Comment by mbelhassen** [comment]
i have install the 1.7.1 panel right now , i have to wait the miner to connect and we will see if problem persist or not

**Comment by mbelhassen** [comment]
Stack trace:
#0 /home/........../www/wp-content/master/internalPages/statisticsAjax.php(38): PDO->query('SELECT ms_statu...')
#1 /home/........../www/wp-content/master/page-loader.php(5): include('/home/..........')
#2 {main}
  thrown in /home/................./www/wp-content/master/internalPages/statisticsAjax.php on line 38
[06-Jun-2023 21:51:27 Europe/Paris] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 11 database disk image is malformed in /home/...................../www/wp-content/master/internalPages/statisticsAjax.php:38

This is error i have in error log

**Comment by UnamSanctam** [comment]
Could be a WordPress problem, I have seen it before because of that. Or there's some general problem with your disk or permission.
